services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mercheazy_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/mercheazy-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  db:
    image: 'postgres:17'
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mercheazy-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
