spring:
  app:
    name: mercheazy

  flyway:
    enabled: false

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:mercheazy-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}