spring:
  app:
    name: mercheazy

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:mercheazy-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  security:
    username: ${ADMIN_USERNAME:mercheazy}
    password: ${ADMIN_PASSWORD:admin}
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000

cloudinary:
  url: cloudinary://${CN_KEY}:${CN_SECRET}@${CN_NAME}