spring:
  app:
    name: mercheazy

  profiles:
    active: dev

  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:mercheazy_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  security:
    username: ${ADMIN_USERNAME:mercheazy}
    password: ${ADMIN_PASSWORD:admin}
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

cloudinary:
  url: cloudinary://${CN_KEY}:${CN_SECRET}@${CN_NAME}