spring:
  flyway:
    enabled: false

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: false

  sql:
    init:
      mode: never