spring:
  app:
    name: mercheazy

  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:mercheazy-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000