spring:
  app:
    name: mercheazy
    base-url: ${BASE_URL:http://localhost:8080}

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:mercheazy_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  security:
    username: ${ADMIN_USERNAME:mercheazy}
    password: ${ADMIN_PASSWORD:admin}
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI:http://localhost:4200/oauth2/callback}
            scope:
              - email
              - profile

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  url: cloudinary://${CN_KEY}:${CN_SECRET}@${CN_NAME}