-- public.mercheazy_user definition

-- Drop table

-- DROP TABLE public.mercheazy_user;

CREATE TABLE public.mercheazy_user (
	u_create_date timestamp(6) NOT NULL,
	u_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	u_update_date timestamp(6) NOT NULL,
	u_email varchar(255) NOT NULL,
	u_password varchar(255) NOT NULL,
	u_role varchar(255) NOT NULL,
	u_username varchar(255) NOT NULL,
	CONSTRAINT mercheazy_user_pkey PRIMARY KEY (u_id),
	CONSTRAINT mercheazy_user_u_email_key UNIQUE (u_email),
	CONSTRAINT mercheazy_user_u_role_check CHECK (((u_role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying, 'CREATOR'::character varying, 'MODERATOR'::character varying])::text[]))),
	CONSTRAINT mercheazy_user_u_username_key UNIQUE (u_username)
);